Drop table if exists fact;
Drop table if exists product;
Drop table if exists supplier;
Drop table if exists customer;
Drop table if exists store;
Drop table if exists timing;

CREATE TABLE PRODUCT (
PRODUCT_ID VARCHAR(10) NOT NULL,
PRODUCT_NAME VARCHAR(50) NOT NULL,
PRIMARY KEY (PRODUCT_ID)
);

CREATE TABLE SUPPLIER (
SUPPLIER_ID VARCHAR(10) NOT NULL,
SUPPLIER_NAME VARCHAR(50) NOT NULL,
PRIMARY KEY (SUPPLIER_ID)
);

CREATE TABLE STORE (
STORE_ID VARCHAR(10) NOT NULL,
STORE_NAME VARCHAR(50) NOT NULL,
PRIMARY KEY (STORE_ID)
);

CREATE TABLE CUSTOMER (
CUSTOMER_ID VARCHAR(10) NOT NULL,
CUSTOMER_NAME VARCHAR(50) NOT NULL,
PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE TIMING (
TIMING_ID DATE NOT NULL,
DAYs NUMERIC(3) NOT NULL,
MONTHs NUMERIC(2) NOT NULL,
QUARTERs NUMERIC(4) NOT NULL,
PRIMARY KEY(TIMING_ID)
);

CREATE TABLE FACT (
sales float(20) NOT NULL, 
FK_PRODUCT_ID VARCHAR(10) NOT NULL,
FK_SUPPLIER_ID VARCHAR(10) NOT NULL,
FK_date date NOT NULL,
FK_STORE_ID VARCHAR(10) NOT NULL,
FK_CUSTOMER_ID VARCHAR(10) NOT NULL,
Quantity NUMERIC(6) NOT NULL,
FOREIGN KEY (FK_PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID),
FOREIGN KEY (FK_SUPPLIER_ID) REFERENCES SUPPLIER(SUPPLIER_ID),
FOREIGN KEY (FK_date) REFERENCES TIMING(TIMING_ID),
FOREIGN KEY (FK_STORE_ID) REFERENCES STORE(STORE_ID),
FOREIGN KEY (FK_CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);
